import path from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'
import StyleDictionary from 'style-dictionary'
import { formattedVariables } from 'style-dictionary/utils'

// Normalized to forward slashes so the paths stay valid glob patterns on Windows.
const packageRoot = fileURLToPath(new URL('..', import.meta.url)).replaceAll('\\', '/')

// The `macvue` prefix below is also hardcoded inside color-mix()/var() string
// values in tokens/semantic/light.json and dark.json; keep them in sync when renaming.
const PREFIX = 'macvue'

const HEADER = '/* Generated by scripts/build-tokens.mjs — do not edit. */'

StyleDictionary.registerTransform({
  name: 'name/macvue',
  type: 'name',
  transform(token, config) {
    // Drop the top "semantic" segment so semantic vars are `--macvue-label`,
    // not `--macvue-semantic-label`.
    const tokenPath = token.path[0] === 'semantic' ? token.path.slice(1) : token.path
    return [config.prefix, ...tokenPath].join('-')
  },
})

function cssVariables(dictionary, options) {
  return formattedVariables({
    format: 'css',
    dictionary,
    outputReferences: options.outputReferences,
    usesDtcg: true,
    formatting: { indentation: '    ' },
  })
}

StyleDictionary.registerFormat({
  name: 'css/macvue-root',
  format({ dictionary, options }) {
    const vars = cssVariables(dictionary, options)
    return `${HEADER}
@layer macvue.tokens {
  :root {
${vars}
  }

  [data-macvue-appearance='light'] {
    color-scheme: light;
  }
}
`
  },
})

StyleDictionary.registerFormat({
  name: 'css/macvue-dark',
  format({ dictionary, options }) {
    const vars = cssVariables(dictionary, options)
    return `${HEADER}
@layer macvue.tokens {
  [data-macvue-appearance='dark'] {
    color-scheme: dark;
${vars}
  }

  @media (prefers-color-scheme: dark) {
    [data-macvue-appearance='auto'] {
      color-scheme: dark;
${vars.split('\n').map(line => `  ${line}`).join('\n')}
    }
  }
}
`
  },
})

StyleDictionary.registerFormat({
  name: 'ts/macvue-token-names',
  format({ dictionary }) {
    const names = dictionary.allTokens.map(token => `--${token.name}`)
    const union = names.map(name => `  | '${name}'`).join('\n')
    const list = names.map(name => `  '${name}',`).join('\n')
    return `${HEADER}

export type MacvueTokenName =
${union}

export const macvueTokenNames = [
${list}
] as const
`
  },
})

export async function buildTokens(outDir = path.join(packageRoot, 'src')) {
  const light = new StyleDictionary({
    usesDtcg: true,
    source: [
      `${packageRoot}tokens/ref/*.json`,
      `${packageRoot}tokens/semantic/base.json`,
      `${packageRoot}tokens/semantic/light.json`,
      `${packageRoot}tokens/component/*.json`,
    ],
    platforms: {
      css: {
        prefix: PREFIX,
        transforms: ['name/macvue'],
        buildPath: `${outDir}/styles/`,
        files: [
          {
            destination: 'tokens.gen.css',
            format: 'css/macvue-root',
            options: { outputReferences: true },
          },
        ],
      },
      ts: {
        prefix: PREFIX,
        transforms: ['name/macvue'],
        buildPath: `${outDir}/`,
        files: [
          {
            destination: 'tokens.gen.ts',
            format: 'ts/macvue-token-names',
          },
        ],
      },
    },
  })

  const dark = new StyleDictionary({
    usesDtcg: true,
    // ref tokens are included only to resolve aliases; the file filter below
    // keeps them out of the output so dark overrides stay semantic-only.
    source: [
      `${packageRoot}tokens/ref/*.json`,
      `${packageRoot}tokens/semantic/dark.json`,
    ],
    platforms: {
      css: {
        prefix: PREFIX,
        transforms: ['name/macvue'],
        buildPath: `${outDir}/styles/`,
        files: [
          {
            destination: 'tokens-dark.gen.css',
            format: 'css/macvue-dark',
            filter: token => token.filePath.includes('semantic/dark'),
            options: { outputReferences: true },
          },
        ],
      },
    },
  })

  await light.buildAllPlatforms()
  await dark.buildAllPlatforms()
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1]))
  await buildTokens()
